# Generated by Django 5.2.4 on 2025-07-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title',
        ),
    ]
