# Generated by Django 5.2.4 on 2025-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_remove_banner_text_remove_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
