# Generated by Django 5.2.4 on 2025-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_text_banner_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
