# Generated by Django 5.2.4 on 2025-07-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_banner_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Банер', 'verbose_name_plural': 'Банеры'},
        ),
    ]
