# Generated by Django 5.2.4 on 2025-07-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_alter_banner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
