# Generated by Django 5.2.4 on 2025-07-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_orderitem_order_remove_orderitem_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
    ]
