# Generated by Django 5.2.4 on 2025-07-24 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_messages_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ManyToManyField(related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
