# Generated by Django 5.2.4 on 2025-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_messages_user_messages_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='is_read',
        ),
        migrations.AddField(
            model_name='customuser',
            name='unread_messages',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
