# Generated by Django 5.2.4 on 2025-07-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_messages_is_read_customuser_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unread_messages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
