# Generated by Django 5.2.4 on 2025-07-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_customuser_favorites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='patronymic',
            new_name='middle_name',
        ),
    ]
