# Generated by Django 5.2.4 on 2025-07-20 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_subcategory_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='servicesubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.servicecategory'),
        ),
    ]
