# Generated by Django 5.2.4 on 2025-07-21 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_service_category_alter_service_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Основна категорія послуг',
                'verbose_name_plural': 'Основні категорії послуг',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Послуга', 'verbose_name_plural': 'Послуги'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Категорія послуг', 'verbose_name_plural': 'Категорії послуг'},
        ),
        migrations.AlterModelOptions(
            name='serviceoption',
            options={'verbose_name': 'Опція послуги', 'verbose_name_plural': 'Опції послуг'},
        ),
        migrations.AlterModelOptions(
            name='servicesubcategory',
            options={'verbose_name': 'Підкатегорія послуг', 'verbose_name_plural': 'Підкатегорії послуг'},
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(decimal_places=2, help_text='Мінімальна ціна від', max_digits=10),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='option_name',
            field=models.CharField(help_text='Наприклад: 100 шт., формат A4, ламінування тощо.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='catalog.mainservicecategory'),
        ),
    ]
