# Generated by Django 5.2.4 on 2025-07-21 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_mainservicecategory_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='servicesubcategory',
            name='category',
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.servicecategory'),
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.servicecategory'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.DeleteModel(
            name='MainServiceCategory',
        ),
        migrations.DeleteModel(
            name='ServiceSubCategory',
        ),
    ]
