# Generated by Django 5.2.4 on 2025-07-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='parent',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='childrens', to='catalog.servicecategory'),
        ),
    ]
