# Generated by Django 5.2.4 on 2025-07-21 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_servicecategory_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='parents',
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.servicecategory'),
        ),
    ]
