# Generated by Django 5.2.4 on 2025-07-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_service_image2_service_image3_service_image4_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceoption',
            options={'ordering': ['category', 'option_name'], 'verbose_name': 'Опція послуги', 'verbose_name_plural': 'Опції послуг'},
        ),
        migrations.RemoveField(
            model_name='serviceoption',
            name='service',
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='option_name',
            field=models.CharField(help_text='Наприклад: глянцеве, A4, 100 шт.', max_length=255),
        ),
        migrations.CreateModel(
            name='ServiceOptionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Тип опції, наприклад: Покриття, Формат, Кількість', max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_categories', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Категорія опцій',
                'verbose_name_plural': 'Категорії опцій',
            },
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.serviceoptioncategory'),
            preserve_default=False,
        ),
    ]
