# Generated by Django 5.2.4 on 2025-07-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_serviceoption_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceoption',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Опція послуги', 'verbose_name_plural': 'Опції послуг'},
        ),
        migrations.RenameField(
            model_name='serviceoption',
            old_name='option_name',
            new_name='title',
        ),
    ]
