# Generated by Django 5.2.4 on 2025-07-25 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_serviceoption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.servicecategory', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Забраження 1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Забраження 2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Забраження 3'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Забраження 4'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Забраження 5'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Забраження 6'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(decimal_places=2, help_text='Мінімальна ціна від', max_digits=10, verbose_name='Ціна починаючи з'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.servicecategory', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='title',
            field=models.CharField(max_length=255, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.serviceoptioncategory', verbose_name='Категорія опції'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ціна'),
        ),
        migrations.AlterField(
            model_name='serviceoption',
            name='title',
            field=models.CharField(help_text='Наприклад: глянцеве, A4, 100 шт.', max_length=255, verbose_name='Назва опції'),
        ),
        migrations.AlterField(
            model_name='serviceoptioncategory',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_categories', to='catalog.service', verbose_name='Послуга'),
        ),
        migrations.AlterField(
            model_name='serviceoptioncategory',
            name='title',
            field=models.CharField(help_text='Тип опції, наприклад: Покриття, Формат, Кількість', max_length=255, verbose_name='Тип опції'),
        ),
    ]
