# Generated by Django 5.2.4 on 2025-07-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_service_category_alter_service_description_and_more'),
        ('orders', '0006_remove_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='options',
            field=models.ManyToManyField(blank=True, to='catalog.serviceoption', verbose_name='Обрані опції'),
        ),
    ]
